M48
; DRILL file {KiCad 7.0.2} date Tue May 30 09:54:31 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-05-30T09:54:31-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0827
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0906
%
G90
G05
T1
X1.3189Y-1.2715
X3.5689Y-2.0555
X6.5689Y-2.0555
X8.8189Y-1.2715
T2
X2.0765Y-2.6978
X8.8229Y-2.6965
T0
M30
